# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分類', 'verbose_name_plural': '分類'},
        ),
        migrations.AddField(
            model_name='sausage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
