# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sausage', '0002_auto_20170306_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sausage',
            options={'ordering': ['-created'], 'verbose_name': '香腸', 'verbose_name_plural': '香腸'},
        ),
    ]
