# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sausage', '0003_auto_20170323_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sausage',
            old_name='desription',
            new_name='description',
        ),
    ]
